2018-01-12 13:18:21,078:WARNING:app.py:3709::Caught signal: 2
2018-01-12 14:14:49,552:WARNING:app.py:3709::Caught signal: 2
2018-01-12 14:27:21,082:WARNING:app.py:3709::Caught signal: 2
2018-01-12 14:28:01,961:INFO:app.py:3975::log test
2018-01-12 14:28:24,096:INFO:app.py:3975::log test
2018-01-12 14:28:24,116:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:28:24,117:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:28:24,118:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:28:24,124:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:28:24,125:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:28:36,094:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:28:36,098:INFO:app.py:3317::RootHandler.get
2018-01-12 14:28:36,098:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:28:36,098:INFO:app.py:326::header keys...
2018-01-12 14:28:36,098:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:28:36,099:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:28:36,099:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:28:36,099:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:28:36,099:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:28:36,099:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:28:36,099:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:28:36,099:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:28:36,100:INFO:app.py:332::cas_server: [None]
2018-01-12 14:28:36,100:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:28:36,100:INFO:app.py:360::self.username: nik
2018-01-12 14:28:36,102:INFO:app.py:366::self.userid: 501
2018-01-12 14:28:36,164:INFO:app.py:374::gid: 20
2018-01-12 14:28:36,165:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:28:36,165:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:28:36,165:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:28:36,170:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:28:36,171:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:28:36,172:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:28:36,172:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:28:36,172:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:28:36,172:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:28:36,173:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:28:36,173:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:28:36,198:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:28:36,204:INFO:hdf5db.py:548::initializing file
2018-01-12 14:28:36,252:INFO:hdf5db.py:570::visit: public name: Group
2018-01-12 14:28:36,256:INFO:hdf5db.py:570::visit: test name: Group
2018-01-12 14:28:36,257:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:28:36,261:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:28:36,261:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:28:36,261:INFO:app.py:3281::self.userid: 501
2018-01-12 14:28:36,261:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:28:36,262:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:28:36,279:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:30:35,794:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:30:35,800:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:30:35,800:INFO:app.py:326::header keys...
2018-01-12 14:30:35,801:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:30:35,801:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:30:35,801:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:30:35,801:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:30:35,801:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:30:35,801:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:30:35,802:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:30:35,802:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:30:35,802:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:30:35,802:INFO:app.py:332::cas_server: [None]
2018-01-12 14:30:35,802:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:30:35,803:INFO:app.py:360::self.username: nik
2018-01-12 14:30:35,803:INFO:app.py:366::self.userid: 501
2018-01-12 14:30:35,887:INFO:app.py:374::gid: 20
2018-01-12 14:30:35,887:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:30:35,888:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:30:35,888:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:30:35,890:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:30:35,891:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:30:35,891:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:30:35,891:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:30:35,892:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:30:35,892:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:30:35,893:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups?_=1515796235605 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:30:35,896:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:30:35,899:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:30:35,904:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:30:35,906:INFO:hdf5db.py:3164::db.getCollection(groups)
2018-01-12 14:30:35,908:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:30:35,934:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:30:36,047:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:30:36,048:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:30:36,048:INFO:app.py:326::header keys...
2018-01-12 14:30:36,049:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:30:36,049:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:30:36,049:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:30:36,049:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:30:36,049:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:30:36,049:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:30:36,049:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:30:36,050:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:30:36,050:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:30:36,050:INFO:app.py:332::cas_server: [None]
2018-01-12 14:30:36,050:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:30:36,050:INFO:app.py:360::self.username: nik
2018-01-12 14:30:36,050:INFO:app.py:366::self.userid: 501
2018-01-12 14:30:36,074:INFO:app.py:374::gid: 20
2018-01-12 14:30:36,074:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:30:36,074:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:30:36,075:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:30:36,076:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:30:36,077:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:30:36,077:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:30:36,077:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:30:36,078:INFO:app.py:786::got uuid: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:30:36,078:INFO:app.py:457::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:30:36,078:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:30:36,078:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:30:36,079:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:30:36,079:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:30:36,079:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:30:36,079:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links?_=1515796235610 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:30:36,080:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:30:36,080:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:30:36,081:INFO:app.py:826::self.filePath: ../data/.toc.h5
2018-01-12 14:30:36,081:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:30:36,082:INFO:app.py:831::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:30:36,082:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:30:36,090:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:30:36,098:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:32:05,825:WARNING:app.py:3709::Caught signal: 2
2018-01-12 14:32:05,838:INFO:app.py:3716::Stopping http server
2018-01-12 14:32:05,839:INFO:app.py:3719::Will shutdown in 2 seconds ...
2018-01-12 14:32:05,839:INFO:app.py:3733::closing db
2018-01-12 14:32:07,842:INFO:app.py:3730::Shutdown
2018-01-12 14:33:28,733:INFO:app.py:3975::log test
2018-01-12 14:33:28,751:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:33:28,751:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:33:28,754:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:33:28,761:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:33:28,761:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:33:36,487:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:33:36,488:INFO:app.py:3317::RootHandler.get
2018-01-12 14:33:36,488:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:33:36,488:INFO:app.py:326::header keys...
2018-01-12 14:33:36,488:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:33:36,489:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:33:36,489:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:33:36,489:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:33:36,489:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:33:36,489:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:33:36,489:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:33:36,490:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:33:36,490:INFO:app.py:332::cas_server: [None]
2018-01-12 14:33:36,490:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:33:36,490:INFO:app.py:360::self.username: nik
2018-01-12 14:33:36,491:INFO:app.py:366::self.userid: 501
2018-01-12 14:33:36,561:INFO:app.py:374::gid: 20
2018-01-12 14:33:36,562:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:33:36,562:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:33:36,562:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:33:36,574:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:33:36,574:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:33:36,575:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:33:36,576:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:33:36,577:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:33:36,577:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:33:36,577:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:33:36,580:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:33:36,599:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:33:36,614:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:33:36,614:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:33:36,614:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:33:36,615:INFO:app.py:3281::self.userid: 501
2018-01-12 14:33:36,615:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:33:36,615:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:33:36,644:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:33:55,260:INFO:app.py:3975::log test
2018-01-12 14:33:55,277:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:33:55,277:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:33:55,278:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:33:55,283:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:33:55,284:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:33:57,208:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:33:57,209:INFO:app.py:3317::RootHandler.get
2018-01-12 14:33:57,210:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:33:57,211:INFO:app.py:326::header keys...
2018-01-12 14:33:57,211:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:33:57,212:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:33:57,212:INFO:app.py:328::header[Cache-Control]: max-age=0
2018-01-12 14:33:57,213:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:33:57,213:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:33:57,214:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:33:57,214:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:33:57,215:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:33:57,215:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:33:57,215:INFO:app.py:332::cas_server: [None]
2018-01-12 14:33:57,216:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:33:57,216:INFO:app.py:360::self.username: nik
2018-01-12 14:33:57,218:INFO:app.py:366::self.userid: 501
2018-01-12 14:33:57,266:INFO:app.py:374::gid: 20
2018-01-12 14:33:57,266:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:33:57,267:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:33:57,267:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:33:57,268:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:33:57,268:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:33:57,268:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:33:57,268:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:33:57,269:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:33:57,269:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:33:57,269:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:33:57,269:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:33:57,270:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:33:57,271:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:33:57,272:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:33:57,272:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:33:57,272:INFO:app.py:3281::self.userid: 501
2018-01-12 14:33:57,272:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:33:57,273:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:33:57,285:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:34:00,216:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:34:00,217:INFO:app.py:3317::RootHandler.get
2018-01-12 14:34:00,217:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:34:00,217:INFO:app.py:326::header keys...
2018-01-12 14:34:00,217:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:34:00,218:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:34:00,218:INFO:app.py:328::header[Cache-Control]: max-age=0
2018-01-12 14:34:00,218:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:34:00,218:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:34:00,218:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:34:00,218:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:34:00,219:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:34:00,219:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:34:00,219:INFO:app.py:332::cas_server: [None]
2018-01-12 14:34:00,219:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:34:00,219:INFO:app.py:360::self.username: nik
2018-01-12 14:34:00,220:INFO:app.py:366::self.userid: 501
2018-01-12 14:34:00,239:INFO:app.py:374::gid: 20
2018-01-12 14:34:00,239:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:34:00,239:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:34:00,239:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:34:00,239:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:34:00,240:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:34:00,240:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:34:00,240:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:34:00,240:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:34:00,240:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:34:00,240:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:34:00,241:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:34:00,241:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:34:00,241:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:34:00,242:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:34:00,242:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:34:00,242:INFO:app.py:3281::self.userid: 501
2018-01-12 14:34:00,242:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:34:00,242:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:34:00,265:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:34:22,336:INFO:app.py:3975::log test
2018-01-12 14:34:22,354:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:34:22,354:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:34:22,355:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:34:22,360:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:34:22,360:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:34:24,849:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:34:24,849:INFO:app.py:3317::RootHandler.get
2018-01-12 14:34:24,849:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:34:24,850:INFO:app.py:326::header keys...
2018-01-12 14:34:24,850:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:34:24,850:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:34:24,850:INFO:app.py:328::header[Cache-Control]: max-age=0
2018-01-12 14:34:24,850:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:34:24,851:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:34:24,851:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:34:24,851:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:34:24,851:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:34:24,851:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:34:24,851:INFO:app.py:332::cas_server: [None]
2018-01-12 14:34:24,852:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:34:24,852:INFO:app.py:360::self.username: nik
2018-01-12 14:34:24,853:INFO:app.py:366::self.userid: 501
2018-01-12 14:34:24,876:INFO:app.py:374::gid: 20
2018-01-12 14:34:24,876:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:34:24,877:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:34:24,877:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:34:24,877:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:34:24,878:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:34:24,878:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:34:24,878:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:34:24,878:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:34:24,879:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:34:24,879:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:34:24,879:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:34:24,880:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:34:24,881:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:34:24,882:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:34:24,882:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:34:24,882:INFO:app.py:3281::self.userid: 501
2018-01-12 14:34:24,882:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:34:24,882:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:34:24,903:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:34:27,672:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:34:27,673:INFO:app.py:3317::RootHandler.get
2018-01-12 14:34:27,673:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:34:27,673:INFO:app.py:326::header keys...
2018-01-12 14:34:27,674:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:34:27,674:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:34:27,674:INFO:app.py:328::header[Cache-Control]: max-age=0
2018-01-12 14:34:27,674:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:34:27,675:INFO:app.py:328::header[Upgrade-Insecure-Requests]: 1
2018-01-12 14:34:27,675:INFO:app.py:328::header[Accept]: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
2018-01-12 14:34:27,675:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:34:27,675:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:34:27,675:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:34:27,676:INFO:app.py:332::cas_server: [None]
2018-01-12 14:34:27,676:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:34:27,676:INFO:app.py:360::self.username: nik
2018-01-12 14:34:27,677:INFO:app.py:366::self.userid: 501
2018-01-12 14:34:27,696:INFO:app.py:374::gid: 20
2018-01-12 14:34:27,697:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:34:27,697:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:34:27,697:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:34:27,697:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:34:27,698:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:34:27,698:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:34:27,698:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:34:27,698:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:34:27,698:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:34:27,698:INFO:app.py:478::REQ GET https://127.0.0.1:6050/ {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:34:27,699:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:34:27,699:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:34:27,700:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:34:27,700:INFO:app.py:3279::rootUUID: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:34:27,701:INFO:app.py:3280::self.filePath: ../data/.toc.h5
2018-01-12 14:34:27,701:INFO:app.py:3281::self.userid: 501
2018-01-12 14:34:27,701:INFO:app.py:3285::acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:34:27,701:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:34:27,714:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:34:54,059:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:34:54,061:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:34:54,061:INFO:app.py:326::header keys...
2018-01-12 14:34:54,061:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:34:54,061:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:34:54,061:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:34:54,062:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:34:54,062:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:34:54,062:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:34:54,062:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:34:54,062:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:34:54,062:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:34:54,062:INFO:app.py:332::cas_server: [None]
2018-01-12 14:34:54,063:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:34:54,063:INFO:app.py:360::self.username: nik
2018-01-12 14:34:54,063:INFO:app.py:366::self.userid: 501
2018-01-12 14:34:54,095:INFO:app.py:374::gid: 20
2018-01-12 14:34:54,095:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:34:54,095:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:34:54,095:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:34:54,096:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:34:54,097:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:34:54,097:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:34:54,097:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:34:54,097:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:34:54,097:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:34:54,098:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups?_=1515796493945 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:34:54,098:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:34:54,100:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:34:54,101:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:34:54,102:INFO:hdf5db.py:3164::db.getCollection(groups)
2018-01-12 14:34:54,107:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:34:54,210:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:34:54,289:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:34:54,289:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:34:54,289:INFO:app.py:326::header keys...
2018-01-12 14:34:54,289:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:34:54,290:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:34:54,290:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:34:54,290:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:34:54,290:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:34:54,290:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:34:54,291:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:34:54,291:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:34:54,291:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:34:54,291:INFO:app.py:332::cas_server: [None]
2018-01-12 14:34:54,291:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:34:54,291:INFO:app.py:360::self.username: nik
2018-01-12 14:34:54,292:INFO:app.py:366::self.userid: 501
2018-01-12 14:34:54,316:INFO:app.py:374::gid: 20
2018-01-12 14:34:54,316:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:34:54,316:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:34:54,317:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:34:54,317:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:34:54,318:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:34:54,318:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:34:54,318:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:34:54,319:INFO:app.py:786::got uuid: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:34:54,319:INFO:app.py:457::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:34:54,319:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:34:54,319:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:34:54,319:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:34:54,320:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:34:54,320:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:34:54,320:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links?_=1515796493950 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:34:54,320:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:34:54,321:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:34:54,321:INFO:app.py:826::self.filePath: ../data/.toc.h5
2018-01-12 14:34:54,322:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:34:54,322:INFO:app.py:831::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:34:54,322:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:34:54,331:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:35:16,175:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:35:16,176:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:35:16,176:INFO:app.py:326::header keys...
2018-01-12 14:35:16,177:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:35:16,177:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:35:16,177:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:35:16,177:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:35:16,177:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:35:16,178:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:35:16,178:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:35:16,178:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:35:16,178:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:35:16,178:INFO:app.py:332::cas_server: [None]
2018-01-12 14:35:16,179:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:35:16,179:INFO:app.py:360::self.username: nik
2018-01-12 14:35:16,179:INFO:app.py:366::self.userid: 501
2018-01-12 14:35:16,208:INFO:app.py:374::gid: 20
2018-01-12 14:35:16,208:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:35:16,208:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:35:16,209:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:35:16,210:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:35:16,210:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:35:16,210:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:35:16,211:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:35:16,211:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:35:16,211:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:35:16,211:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups?_=1515796516072 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:35:16,211:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:35:16,224:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:35:16,226:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:35:16,227:INFO:hdf5db.py:3164::db.getCollection(groups)
2018-01-12 14:35:16,228:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:35:16,251:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:35:16,251:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:35:16,251:INFO:app.py:326::header keys...
2018-01-12 14:35:16,252:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:35:16,252:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:35:16,252:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:35:16,252:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:35:16,252:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:35:16,252:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:35:16,253:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:35:16,253:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:35:16,253:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:35:16,253:INFO:app.py:332::cas_server: [None]
2018-01-12 14:35:16,253:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:35:16,253:INFO:app.py:360::self.username: nik
2018-01-12 14:35:16,254:INFO:app.py:366::self.userid: 501
2018-01-12 14:35:16,290:INFO:app.py:374::gid: 20
2018-01-12 14:35:16,290:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:35:16,290:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:35:16,291:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:35:16,291:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:35:16,291:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:35:16,291:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:35:16,292:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:35:16,292:INFO:app.py:786::got uuid: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:35:16,292:INFO:app.py:457::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:35:16,292:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:35:16,292:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:35:16,293:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:35:16,293:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:35:16,293:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:35:16,293:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links?_=1515796516077 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:35:16,293:INFO:hdf5db.py:163::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:35:16,294:INFO:hdf5db.py:194::Hdf5db __enter
2018-01-12 14:35:16,295:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:35:16,296:INFO:app.py:826::self.filePath: ../data/.toc.h5
2018-01-12 14:35:16,297:INFO:hdf5db.py:713::getUUIDByPath: [/]
2018-01-12 14:35:16,297:INFO:app.py:831::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:35:16,298:INFO:hdf5db.py:198::Hdf5db __exit
2018-01-12 14:35:16,300:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:38:46,615:INFO:app.py:3975::log test
2018-01-12 14:38:46,631:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:38:46,631:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:38:46,632:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:38:46,640:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:38:46,640:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:38:51,954:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:38:51,955:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:38:51,955:INFO:app.py:326::header keys...
2018-01-12 14:38:51,955:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:38:51,956:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:38:51,956:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:38:51,956:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:38:51,956:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:38:51,956:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:38:51,957:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:38:51,957:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:38:51,957:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:38:51,958:INFO:app.py:332::cas_server: [None]
2018-01-12 14:38:51,958:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:38:51,958:INFO:app.py:360::self.username: nik
2018-01-12 14:38:51,961:INFO:app.py:366::self.userid: 501
2018-01-12 14:38:52,010:INFO:app.py:374::gid: 20
2018-01-12 14:38:52,010:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:38:52,011:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:38:52,011:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:38:52,014:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:38:52,015:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:38:52,015:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:38:52,015:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:38:52,016:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:38:52,016:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:38:52,016:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups?_=1515796731806 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:38:52,017:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:38:52,030:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:38:52,030:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,042:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:38:52,043:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (6 members)>
2018-01-12 14:38:52,048:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:38:52,049:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:38:52,050:INFO:hdf5db.py:438::acl: None
2018-01-12 14:38:52,050:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:38:52,051:INFO:hdf5db.py:3295::db.getCollection(groups)
2018-01-12 14:38:52,051:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,053:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:38:52,066:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:38:52,236:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:38:52,236:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:38:52,237:INFO:app.py:326::header keys...
2018-01-12 14:38:52,237:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:38:52,237:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:38:52,237:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:38:52,237:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:38:52,238:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:38:52,238:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:38:52,238:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:38:52,238:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:38:52,238:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:38:52,238:INFO:app.py:332::cas_server: [None]
2018-01-12 14:38:52,239:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:38:52,239:INFO:app.py:360::self.username: nik
2018-01-12 14:38:52,239:INFO:app.py:366::self.userid: 501
2018-01-12 14:38:52,261:INFO:app.py:374::gid: 20
2018-01-12 14:38:52,262:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:38:52,262:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:38:52,262:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:38:52,263:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:38:52,263:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:38:52,263:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:38:52,264:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:38:52,264:INFO:app.py:786::got uuid: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:38:52,264:INFO:app.py:457::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:38:52,264:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:38:52,265:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:38:52,265:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:38:52,265:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:38:52,265:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:38:52,265:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links?_=1515796731811 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:38:52,266:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:38:52,267:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:38:52,267:INFO:app.py:826::self.filePath: ../data/.toc.h5
2018-01-12 14:38:52,267:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,268:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:38:52,268:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:38:52,269:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:38:52,269:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:38:52,269:INFO:hdf5db.py:438::acl: None
2018-01-12 14:38:52,270:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:38:52,270:INFO:app.py:831::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:38:52,270:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,270:INFO:hdf5db.py:738::getPathByUUID: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:38:52,271:INFO:hdf5db.py:740::obj.file.filename: ../data/.toc.h5
2018-01-12 14:38:52,271:INFO:app.py:833::self.userid: 501
2018-01-12 14:38:52,271:INFO:app.py:834::current_user_acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:38:52,271:INFO:hdf5db.py:3211::db.getLinkItems(ee168386-f7e7-11e7-a6cf-b8e8562787ba)
2018-01-12 14:38:52,271:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,272:INFO:hdf5db.py:552::initFile
2018-01-12 14:38:52,272:INFO:hdf5db.py:806::getGroupObjByUuid(ee168386-f7e7-11e7-a6cf-b8e8562787ba)
2018-01-12 14:38:52,274:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:38:52,278:INFO:app.py:866::item: {'title': 'public', 'class': 'H5L_TYPE_HARD', 'id': 'ee1de590-f7e7-11e7-92bd-b8e8562787ba', 'href': 'https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links/public', 'collection': 'groups'}
2018-01-12 14:38:52,278:INFO:app.py:868::parent_group_uuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:38:52,294:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:41:44,811:INFO:app.py:3975::log test
2018-01-12 14:41:44,829:INFO:passwordUtil.py:56::getAuthClient
2018-01-12 14:41:44,829:INFO:passwordUtil.py:58::password_uri:../util/admin/passwd.h5
2018-01-12 14:41:44,830:INFO:authFile.py:36::AuthFile class init(../util/admin/passwd.h5)
2018-01-12 14:41:44,835:INFO:app.py:4028::INITIALIZING...
2018-01-12 14:41:44,835:INFO:app.py:4029::Running SSL on port: 6050 (SSL)
2018-01-12 14:41:55,899:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:41:55,900:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:41:55,900:INFO:app.py:326::header keys...
2018-01-12 14:41:55,900:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:41:55,900:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:41:55,901:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:41:55,901:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:41:55,901:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:41:55,901:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:41:55,901:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:41:55,902:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:41:55,902:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:41:55,902:INFO:app.py:332::cas_server: [None]
2018-01-12 14:41:55,903:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:41:55,904:INFO:app.py:360::self.username: nik
2018-01-12 14:41:55,905:INFO:app.py:366::self.userid: 501
2018-01-12 14:41:55,945:INFO:app.py:374::gid: 20
2018-01-12 14:41:55,946:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:41:55,947:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:41:55,947:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:41:55,948:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:41:55,949:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:41:55,949:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:41:55,949:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:41:55,949:INFO:app.py:457::self.reqUuid: None
2018-01-12 14:41:55,949:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:41:55,950:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups?_=1515796915806 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:41:55,951:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:41:55,952:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:41:55,952:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:55,955:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:41:55,956:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:55,956:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:41:55,956:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:55,957:INFO:hdf5db.py:438::acl: None
2018-01-12 14:41:55,957:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:55,957:INFO:hdf5db.py:3295::db.getCollection(groups)
2018-01-12 14:41:55,957:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:55,958:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:41:55,971:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:41:56,022:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:41:56,023:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:41:56,023:INFO:app.py:326::header keys...
2018-01-12 14:41:56,023:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:41:56,023:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:41:56,023:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:41:56,023:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:41:56,024:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:41:56,027:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:41:56,027:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:41:56,027:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:41:56,027:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:41:56,028:INFO:app.py:332::cas_server: [None]
2018-01-12 14:41:56,028:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:41:56,028:INFO:app.py:360::self.username: nik
2018-01-12 14:41:56,029:INFO:app.py:366::self.userid: 501
2018-01-12 14:41:56,048:INFO:app.py:374::gid: 20
2018-01-12 14:41:56,049:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:41:56,049:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:41:56,049:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:41:56,050:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:41:56,050:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:41:56,050:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:41:56,050:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:41:56,050:INFO:app.py:786::got uuid: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:41:56,051:INFO:app.py:457::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:41:56,051:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:41:56,051:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:41:56,051:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:41:56,051:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:41:56,051:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:41:56,052:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links?_=1515796915811 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:41:56,052:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:41:56,052:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:41:56,053:INFO:app.py:826::self.filePath: ../data/.toc.h5
2018-01-12 14:41:56,053:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:56,053:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:41:56,054:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:56,054:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:41:56,054:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:56,054:INFO:hdf5db.py:438::acl: None
2018-01-12 14:41:56,055:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:41:56,055:INFO:app.py:831::self.reqUuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:41:56,055:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:56,055:INFO:hdf5db.py:738::getPathByUUID: [ee168386-f7e7-11e7-a6cf-b8e8562787ba]
2018-01-12 14:41:56,056:INFO:hdf5db.py:740::obj.file.filename: ../data/.toc.h5
2018-01-12 14:41:56,056:INFO:app.py:833::self.userid: 501
2018-01-12 14:41:56,056:INFO:app.py:834::current_user_acl: {'userid': 0, 'create': 1, 'read': 1, 'update': 1, 'delete': 1, 'readACL': 1, 'updateACL': 1}
2018-01-12 14:41:56,056:INFO:hdf5db.py:3211::db.getLinkItems(ee168386-f7e7-11e7-a6cf-b8e8562787ba)
2018-01-12 14:41:56,056:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:56,057:INFO:hdf5db.py:552::initFile
2018-01-12 14:41:56,057:INFO:hdf5db.py:806::getGroupObjByUuid(ee168386-f7e7-11e7-a6cf-b8e8562787ba)
2018-01-12 14:41:56,059:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:41:56,060:INFO:app.py:866::item: {'title': 'public', 'class': 'H5L_TYPE_HARD', 'id': 'ee1de590-f7e7-11e7-92bd-b8e8562787ba', 'href': 'https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links/public', 'collection': 'groups'}
2018-01-12 14:41:56,060:INFO:app.py:868::parent_group_uuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:41:56,087:INFO:app.py:866::item: {'title': 'test', 'class': 'H5L_TYPE_HARD', 'id': 'ee1e819e-f7e7-11e7-ace7-b8e8562787ba', 'href': 'https://127.0.0.1:6050/groups/ee168386-f7e7-11e7-a6cf-b8e8562787ba/links/test', 'collection': 'groups'}
2018-01-12 14:41:56,088:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:41:56,089:INFO:app.py:868::parent_group_uuid: ee168386-f7e7-11e7-a6cf-b8e8562787ba
2018-01-12 14:42:02,198:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 14:42:02,198:INFO:app.py:199::filepath: public
2018-01-12 14:42:02,199:INFO:app.py:200::h5path: 
2018-01-12 14:42:02,199:INFO:app.py:214::message: True
2018-01-12 14:42:02,200:INFO:app.py:215::uuid: False
2018-01-12 14:42:02,209:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:02,209:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:42:02,209:INFO:app.py:326::header keys...
2018-01-12 14:42:02,209:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:42:02,209:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:42:02,210:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:42:02,210:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:42:02,210:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:42:02,210:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:42:02,210:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:42:02,210:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:42:02,210:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:42:02,211:INFO:app.py:332::cas_server: [None]
2018-01-12 14:42:02,211:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:42:02,211:INFO:app.py:360::self.username: nik
2018-01-12 14:42:02,211:INFO:app.py:366::self.userid: 501
2018-01-12 14:42:02,229:INFO:app.py:374::gid: 20
2018-01-12 14:42:02,229:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:42:02,229:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:42:02,230:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:42:02,230:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:42:02,230:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:42:02,231:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:42:02,231:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:42:02,231:INFO:app.py:786::got uuid: [False]
2018-01-12 14:42:02,231:INFO:app.py:457::self.reqUuid: False
2018-01-12 14:42:02,232:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:42:02,232:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:42:02,232:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:42:02,232:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:42:02,233:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:42:02,234:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915814 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:42:02,234:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:42:02,235:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:42:02,235:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:02,236:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:42:02,236:INFO:app.py:2719::self.reqUuid: False
2018-01-12 14:42:02,236:INFO:app.py:2720::self.userid: 501
2018-01-12 14:42:02,237:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:02,237:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:42:02,237:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:02,238:INFO:hdf5db.py:438::acl: None
2018-01-12 14:42:02,238:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:02,238:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:02,239:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:02,239:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:02,239:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:02,240:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 14:42:02,240:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 14:42:02,241:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:42:02,241:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 14:42:02,242:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:02,254:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:42:05,833:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 14:42:05,833:INFO:app.py:199::filepath: test
2018-01-12 14:42:05,833:INFO:app.py:200::h5path: 
2018-01-12 14:42:05,833:INFO:app.py:214::message: True
2018-01-12 14:42:05,833:INFO:app.py:215::uuid: False
2018-01-12 14:42:05,842:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:05,842:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:42:05,842:INFO:app.py:326::header keys...
2018-01-12 14:42:05,842:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:42:05,842:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:42:05,843:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:42:05,843:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:42:05,843:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:42:05,843:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:42:05,843:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:42:05,843:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:42:05,843:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:42:05,843:INFO:app.py:332::cas_server: [None]
2018-01-12 14:42:05,844:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:42:05,844:INFO:app.py:360::self.username: nik
2018-01-12 14:42:05,844:INFO:app.py:366::self.userid: 501
2018-01-12 14:42:05,860:INFO:app.py:374::gid: 20
2018-01-12 14:42:05,860:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:42:05,861:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:42:05,861:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:42:05,861:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:42:05,861:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:42:05,862:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:42:05,862:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:42:05,862:INFO:app.py:786::got uuid: [False]
2018-01-12 14:42:05,862:INFO:app.py:457::self.reqUuid: False
2018-01-12 14:42:05,862:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:42:05,862:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:42:05,863:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:42:05,863:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:42:05,863:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:42:05,863:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915816 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:42:05,863:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:42:05,864:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:42:05,864:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:05,864:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:42:05,865:INFO:app.py:2719::self.reqUuid: False
2018-01-12 14:42:05,865:INFO:app.py:2720::self.userid: 501
2018-01-12 14:42:05,865:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:05,865:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:42:05,865:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:05,866:INFO:hdf5db.py:438::acl: None
2018-01-12 14:42:05,866:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:05,866:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:05,866:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:05,867:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:05,867:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:05,868:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 14:42:05,868:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 14:42:05,868:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:42:05,869:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 14:42:05,869:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:05,880:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:42:56,995:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 14:42:56,996:INFO:app.py:199::filepath: public
2018-01-12 14:42:56,996:INFO:app.py:200::h5path: 
2018-01-12 14:42:56,997:INFO:app.py:214::message: True
2018-01-12 14:42:56,997:INFO:app.py:215::uuid: False
2018-01-12 14:42:57,005:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:57,006:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:42:57,006:INFO:app.py:326::header keys...
2018-01-12 14:42:57,006:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:42:57,006:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:42:57,006:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:42:57,007:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:42:57,007:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:42:57,007:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:42:57,007:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:42:57,007:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:42:57,007:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:42:57,007:INFO:app.py:332::cas_server: [None]
2018-01-12 14:42:57,008:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:42:57,008:INFO:app.py:360::self.username: nik
2018-01-12 14:42:57,008:INFO:app.py:366::self.userid: 501
2018-01-12 14:42:57,038:INFO:app.py:374::gid: 20
2018-01-12 14:42:57,038:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:42:57,038:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:42:57,038:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:42:57,039:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:42:57,040:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:42:57,040:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:42:57,041:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:42:57,041:INFO:app.py:786::got uuid: [False]
2018-01-12 14:42:57,041:INFO:app.py:457::self.reqUuid: False
2018-01-12 14:42:57,041:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:42:57,041:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:42:57,041:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:42:57,041:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:42:57,042:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:42:57,042:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915818 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:42:57,042:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:42:57,043:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:42:57,043:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:57,044:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:42:57,045:INFO:app.py:2719::self.reqUuid: False
2018-01-12 14:42:57,045:INFO:app.py:2720::self.userid: 501
2018-01-12 14:42:57,045:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:57,045:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:42:57,045:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:57,046:INFO:hdf5db.py:438::acl: None
2018-01-12 14:42:57,046:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:57,046:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:57,047:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:42:57,047:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:57,047:INFO:hdf5db.py:552::initFile
2018-01-12 14:42:57,048:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 14:42:57,049:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 14:42:57,049:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:42:57,050:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 14:42:57,050:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:42:57,108:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:44:42,960:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 14:44:42,962:INFO:app.py:199::filepath: public
2018-01-12 14:44:42,962:INFO:app.py:200::h5path: 
2018-01-12 14:44:42,962:INFO:app.py:214::message: True
2018-01-12 14:44:42,963:INFO:app.py:215::uuid: False
2018-01-12 14:44:42,977:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:44:42,977:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:44:42,977:INFO:app.py:326::header keys...
2018-01-12 14:44:42,978:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:44:42,978:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:44:42,978:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:44:42,979:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:44:42,979:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:44:42,979:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:44:42,979:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:44:42,980:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:44:42,980:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:44:42,980:INFO:app.py:332::cas_server: [None]
2018-01-12 14:44:42,981:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:44:42,981:INFO:app.py:360::self.username: nik
2018-01-12 14:44:42,981:INFO:app.py:366::self.userid: 501
2018-01-12 14:44:43,020:INFO:app.py:374::gid: 20
2018-01-12 14:44:43,021:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:44:43,021:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:44:43,021:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:44:43,023:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:44:43,023:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:44:43,024:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:44:43,024:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:44:43,024:INFO:app.py:786::got uuid: [False]
2018-01-12 14:44:43,024:INFO:app.py:457::self.reqUuid: False
2018-01-12 14:44:43,024:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:44:43,025:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:44:43,025:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:44:43,025:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:44:43,025:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:44:43,025:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915820 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:44:43,025:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:44:43,027:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:44:43,027:INFO:hdf5db.py:552::initFile
2018-01-12 14:44:43,030:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:44:43,030:INFO:app.py:2719::self.reqUuid: False
2018-01-12 14:44:43,030:INFO:app.py:2720::self.userid: 501
2018-01-12 14:44:43,031:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:44:43,031:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:44:43,031:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:44:43,032:INFO:hdf5db.py:438::acl: None
2018-01-12 14:44:43,032:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:44:43,032:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:44:43,033:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:44:43,033:INFO:hdf5db.py:552::initFile
2018-01-12 14:44:43,033:INFO:hdf5db.py:552::initFile
2018-01-12 14:44:43,034:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 14:44:43,034:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 14:44:43,034:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:44:43,036:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 14:44:43,036:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:44:43,194:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 14:47:28,893:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 14:47:28,894:INFO:app.py:199::filepath: test
2018-01-12 14:47:28,894:INFO:app.py:200::h5path: 
2018-01-12 14:47:28,895:INFO:app.py:214::message: True
2018-01-12 14:47:28,895:INFO:app.py:215::uuid: False
2018-01-12 14:47:28,905:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:47:28,906:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 14:47:28,906:INFO:app.py:326::header keys...
2018-01-12 14:47:28,907:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 14:47:28,907:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 14:47:28,907:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 14:47:28,907:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 14:47:28,908:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 14:47:28,908:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 14:47:28,908:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 14:47:28,908:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 14:47:28,908:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 14:47:28,909:INFO:app.py:332::cas_server: [None]
2018-01-12 14:47:28,909:INFO:app.py:336::need_authentication: [False]
2018-01-12 14:47:28,909:INFO:app.py:360::self.username: nik
2018-01-12 14:47:28,909:INFO:app.py:366::self.userid: 501
2018-01-12 14:47:28,943:INFO:app.py:374::gid: 20
2018-01-12 14:47:28,944:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 14:47:28,944:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 14:47:28,944:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 14:47:28,946:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 14:47:28,946:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 14:47:28,946:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 14:47:28,946:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 14:47:28,947:INFO:app.py:786::got uuid: [False]
2018-01-12 14:47:28,947:INFO:app.py:457::self.reqUuid: False
2018-01-12 14:47:28,947:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 14:47:28,947:INFO:app.py:468::can_user_read_file: False
2018-01-12 14:47:28,947:INFO:app.py:534::set_file_ACL(False)
2018-01-12 14:47:28,947:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 14:47:28,947:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 14:47:28,948:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915822 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 14:47:28,949:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 14:47:28,951:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 14:47:28,951:INFO:hdf5db.py:552::initFile
2018-01-12 14:47:28,954:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 14:47:28,954:INFO:app.py:2719::self.reqUuid: False
2018-01-12 14:47:28,955:INFO:app.py:2720::self.userid: 501
2018-01-12 14:47:28,955:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:47:28,956:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 14:47:28,956:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:47:28,957:INFO:hdf5db.py:438::acl: None
2018-01-12 14:47:28,958:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:47:28,958:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:47:28,959:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 14:47:28,959:INFO:hdf5db.py:552::initFile
2018-01-12 14:47:28,960:INFO:hdf5db.py:552::initFile
2018-01-12 14:47:28,960:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 14:47:28,961:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 14:47:28,961:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 14:47:28,962:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 14:47:28,962:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 14:47:28,990:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 15:09:56,940:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 15:09:56,942:INFO:app.py:199::filepath: public
2018-01-12 15:09:56,942:INFO:app.py:200::h5path: 
2018-01-12 15:09:56,943:INFO:app.py:214::message: True
2018-01-12 15:09:56,943:INFO:app.py:215::uuid: False
2018-01-12 15:09:56,955:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 15:09:56,956:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 15:09:56,956:INFO:app.py:326::header keys...
2018-01-12 15:09:56,956:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 15:09:56,957:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 15:09:56,957:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 15:09:56,957:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 15:09:56,957:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 15:09:56,958:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 15:09:56,958:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 15:09:56,958:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 15:09:56,958:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 15:09:56,958:INFO:app.py:332::cas_server: [None]
2018-01-12 15:09:56,959:INFO:app.py:336::need_authentication: [False]
2018-01-12 15:09:56,959:INFO:app.py:360::self.username: nik
2018-01-12 15:09:56,959:INFO:app.py:366::self.userid: 501
2018-01-12 15:09:56,991:INFO:app.py:374::gid: 20
2018-01-12 15:09:56,992:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 15:09:56,992:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 15:09:56,992:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 15:09:57,029:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 15:09:57,030:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 15:09:57,030:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 15:09:57,030:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 15:09:57,031:INFO:app.py:786::got uuid: [False]
2018-01-12 15:09:57,031:INFO:app.py:457::self.reqUuid: False
2018-01-12 15:09:57,031:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 15:09:57,032:INFO:app.py:468::can_user_read_file: False
2018-01-12 15:09:57,032:INFO:app.py:534::set_file_ACL(False)
2018-01-12 15:09:57,032:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 15:09:57,033:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 15:09:57,033:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915824 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 15:09:57,033:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 15:09:57,058:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 15:09:57,059:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:57,096:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 15:09:57,097:INFO:app.py:2719::self.reqUuid: False
2018-01-12 15:09:57,097:INFO:app.py:2720::self.userid: 501
2018-01-12 15:09:57,098:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:57,099:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 15:09:57,099:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:57,099:INFO:hdf5db.py:438::acl: None
2018-01-12 15:09:57,100:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:57,100:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:57,101:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:57,102:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:57,103:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:57,103:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 15:09:57,105:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 15:09:57,105:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 15:09:57,108:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 15:09:57,108:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 15:09:57,276:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 15:09:58,881:INFO:app.py:194::GetUUIDHandler:get() called
2018-01-12 15:09:58,882:INFO:app.py:199::filepath: test
2018-01-12 15:09:58,882:INFO:app.py:200::h5path: 
2018-01-12 15:09:58,882:INFO:app.py:214::message: True
2018-01-12 15:09:58,882:INFO:app.py:215::uuid: False
2018-01-12 15:09:58,892:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 15:09:58,892:INFO:app.py:322::BaseHandler.get_current_user
2018-01-12 15:09:58,893:INFO:app.py:326::header keys...
2018-01-12 15:09:58,893:INFO:app.py:328::header[Host]: 127.0.0.1:6050
2018-01-12 15:09:58,893:INFO:app.py:328::header[Connection]: keep-alive
2018-01-12 15:09:58,893:INFO:app.py:328::header[Accept]: application/json, text/javascript, */*; q=0.01
2018-01-12 15:09:58,893:INFO:app.py:328::header[Origin]: http://127.0.0.1:8080
2018-01-12 15:09:58,894:INFO:app.py:328::header[User-Agent]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
2018-01-12 15:09:58,894:INFO:app.py:328::header[Referer]: http://127.0.0.1:8080/html/
2018-01-12 15:09:58,895:INFO:app.py:328::header[Accept-Encoding]: gzip, deflate, br
2018-01-12 15:09:58,896:INFO:app.py:328::header[Accept-Language]: en-US,en;q=0.9
2018-01-12 15:09:58,896:INFO:app.py:329::remote_ip: 127.0.0.1
2018-01-12 15:09:58,896:INFO:app.py:332::cas_server: [None]
2018-01-12 15:09:58,896:INFO:app.py:336::need_authentication: [False]
2018-01-12 15:09:58,896:INFO:app.py:360::self.username: nik
2018-01-12 15:09:58,896:INFO:app.py:366::self.userid: 501
2018-01-12 15:09:58,912:INFO:app.py:374::gid: 20
2018-01-12 15:09:58,912:INFO:app.py:375::self.usergroupids: [81, 79, 98, 80, 20, 20]
2018-01-12 15:09:58,912:INFO:app.py:651::getFilePath: 127.0.0.1:6050 checkExists: True
2018-01-12 15:09:58,913:INFO:app.py:653::tocFilePath: ../data/.toc.h5
2018-01-12 15:09:58,913:INFO:fileUtil.py:76::getFilePath[127.0.0.1:6050]
2018-01-12 15:09:58,913:INFO:app.py:692::verifyFile: ../data/.toc.h5
2018-01-12 15:09:58,914:INFO:fileUtil.py:268::verifyFile('../data/.toc.h5', False)
2018-01-12 15:09:58,914:INFO:app.py:454::self.filePath: ../data/.toc.h5
2018-01-12 15:09:58,914:INFO:app.py:786::got uuid: [False]
2018-01-12 15:09:58,914:INFO:app.py:457::self.reqUuid: False
2018-01-12 15:09:58,915:INFO:app.py:486::actual file?: ../data/.toc.h5
2018-01-12 15:09:58,915:INFO:app.py:468::can_user_read_file: False
2018-01-12 15:09:58,915:INFO:app.py:534::set_file_ACL(False)
2018-01-12 15:09:58,915:INFO:app.py:535::self.filePath: ../data/.toc.h5
2018-01-12 15:09:58,915:INFO:app.py:472::baseHandler, href: https://127.0.0.1:6050
2018-01-12 15:09:58,915:INFO:app.py:478::REQ GET https://127.0.0.1:6050/groups/False?_=1515796915826 {remote_ip: 127.0.0.1, username: nik}
2018-01-12 15:09:58,916:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 15:09:58,916:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 15:09:58,917:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:58,917:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 15:09:58,918:INFO:app.py:2719::self.reqUuid: False
2018-01-12 15:09:58,918:INFO:app.py:2720::self.userid: 501
2018-01-12 15:09:58,918:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:58,918:INFO:hdf5db.py:432::acl_grp: <HDF5 group "/__db__/{acl}" (0 members)>
2018-01-12 15:09:58,919:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:58,919:INFO:hdf5db.py:438::acl: None
2018-01-12 15:09:58,919:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:58,920:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:58,920:INFO:hdf5db.py:332::self.dbGrp: <HDF5 group "/__db__" (7 members)>
2018-01-12 15:09:58,921:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:58,921:INFO:hdf5db.py:552::initFile
2018-01-12 15:09:58,922:INFO:hdf5db.py:806::getGroupObjByUuid(False)
2018-01-12 15:09:58,922:INFO:hdf5db.py:3096::Group with uuid: False was not found
2018-01-12 15:09:58,923:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 15:09:58,923:INFO:app.py:2726::IOError: 6 Group with uuid: False was not found
2018-01-12 15:09:58,924:INFO:app.py:297::cors_domain: http://127.0.0.1:8080
2018-01-12 15:09:58,936:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
2018-01-12 15:13:35,563:INFO:h5watchdog.py:29::H5EventHandler -- Created file: ../data/tocview.h5
2018-01-12 15:13:35,579:INFO:h5watchdog.py:48::H5EventHandler -- Modified directory: ../data
2018-01-12 15:13:35,829:INFO:app.py:3859::process_queue, got: ../data/tocview.h5
2018-01-12 15:13:35,834:INFO:app.py:3824::updateToc(../data/tocview.h5)
2018-01-12 15:13:35,835:INFO:app.py:3837::base domain: tocview.localhost
2018-01-12 15:13:35,842:INFO:tocUtil.py:90::addTocEntry - domain: tocview.localhost filePath: ../data/tocview.h5
2018-01-12 15:13:35,843:INFO:tocUtil.py:96::tocFile: ../data/.toc.h5
2018-01-12 15:13:35,843:INFO:hdf5db.py:167::init -- filePath: ../data/.toc.h5 mode: r+
2018-01-12 15:13:35,871:INFO:hdf5db.py:200::Hdf5db __enter
2018-01-12 15:13:35,871:INFO:hdf5db.py:552::initFile
2018-01-12 15:13:35,895:INFO:hdf5db.py:746::getUUIDByPath: [/]
2018-01-12 15:13:35,896:INFO:tocUtil.py:116::createExternalLink -- uuid ee168386-f7e7-11e7-a6cf-b8e8562787ba, domain: tocview.localhost, linkName: tocview
2018-01-12 15:13:35,896:INFO:hdf5db.py:552::initFile
2018-01-12 15:13:35,897:INFO:hdf5db.py:552::initFile
2018-01-12 15:13:35,898:INFO:hdf5db.py:806::getGroupObjByUuid(ee168386-f7e7-11e7-a6cf-b8e8562787ba)
2018-01-12 15:13:35,916:INFO:hdf5db.py:204::Hdf5db __exit
2018-01-12 15:13:35,929:INFO:h5watchdog.py:48::H5EventHandler -- Modified file: ../data/.toc.h5
